### ISSUE TITLE
question how to use merge-with-fade.sh

### ISSUE THREAD

**Issue by HyowonHwang** [larsks/ffmpeg-tools#1]
Hi, I am new for this. 
Could you kindly let me know how the usage of merge-with-fade.sh?

**Comment by larsks** [comment]
You just provide the script with a list of videos:

    ./merge-with-fade.sh -o output.mp4 vid1.mp4 vid2.mp4 vid3.mp4

It will create `output.mp4` containing all of the listed video fragments with a fade out/fade in transition between them.

It's been a couple of years since I last looked at this, so it may or may not work with current versions of ffmpeg.  Also, I am not an ffmpeg expert, and this was a bit of a hack. There may be better ways of doing this!
